// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: '${dotenv.env['WEB_API_KEY']}',
    appId: '${dotenv.env['WEB_APP_ID']}',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    authDomain: 'authentication-app-3b226.firebaseapp.com',
    storageBucket: 'authentication-app-3b226.appspot.com',
    measurementId: 'G-VGB2Z33D6E',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: '${dotenv.env['ANDROID_API_KEY']}',
    appId: '${dotenv.env['ANDROID_APP_ID']}',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    storageBucket: 'authentication-app-3b226.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: '${dotenv.env['IOS_API_KEY']}',
    appId: '${dotenv.env['IOS_APP_ID']}',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    storageBucket: 'authentication-app-3b226.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: '${dotenv.env['MACOS_API_KEY']}',
    appId: '${dotenv.env['MACOS_APP_ID']}',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    storageBucket: 'authentication-app-3b226.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: '${dotenv.env['WINDOWS_API_KEY']}',
    appId: '${dotenv.env['WINDOWS_APP_ID']}',
    messagingSenderId: '708982864267',
    projectId: 'authentication-app-3b226',
    authDomain: 'authentication-app-3b226.firebaseapp.com',
    storageBucket: 'authentication-app-3b226.appspot.com',
    measurementId: 'G-2T59NK8M7N',
  );
}
